name: Continous integration

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:   
  gradle:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout project sources
      uses: actions/checkout@v3
    - name: Install compiler tools
      run: |
        sudo apt-get update
        sudo apt-get install cmake openjdk-11-jdk g++ mingw-w64-x86-64-dev mingw-w64-tools g++-mingw-w64-x86-64

    - name: Compile JCDD for Linux
      run: |
        cd JCDD && mkdir build
        ./getlibs.sh
        cmake -B build/
        cmake --build build/

    - name: Compile JCDD for Windows
      run: |
        sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
        sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix
        cd JCDD && mkdir build-win
        ./getlibs-win.sh
        cmake -B build-win/ -DCMAKE_TOOLCHAIN_FILE=./toolchain-x86_64-w64-mingw32.cmake
        cmake --build build-win/
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
    - name: Make gradlew executable
      run: chmod +x ./gradlew
    - name: Run build with Gradle wrapper
      run: ./gradlew build --scan
    - name: Upload build reports
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: build/reports/