name: Build artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-jdbm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install compiler tools
        run: |
          sudo apt-get update
          sudo apt-get install cmake openjdk-11-jdk g++ mingw-w64-i686-dev mingw-w64-x86-64-dev mingw-w64-tools

      - name: Compile UDBM for Linux
        run: |
          cd JDBM && mkdir build
          cmake -B build/
          cmake --build build/

      - name: Compile UDBM for Windows
        run: |
          cd JDBM && mkdir build-win
          cmake -B build-win/
          cmake --build build-win/

      - name: Upload UDBM Linux
        uses: actions/upload-artifact@v2
        with:
          name: jdbm-linux
          path: JDBM/build/lib/*

      - name: Upload UDBM Windows
        uses: actions/upload-artifact@v2
        with:
          name: jdbm-windows
          path: JDBM/build-win/lib/*
