name: Build artifacts

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-DBMLib-jar:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Create jar file
        run: |
          cd DBMLib
          javac lib/DBMLib.java
          jar cfe ../lib/DBMLib.jar lib.DBMLib lib/DBMLib.class
      - name: Upload DBMLib.jar
        uses: actions/upload-artifact@v2
        with:
          name: dbm-jni
          path: lib/DBMLib.jar

  build-dbm-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install compiler tools
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake make
      - name: Clone java JDK
        uses: actions/checkout@v2
        with:
          repository: openjdk/jdk
          path: jdk

      - name: Compile UDBM for Linux
        run: |
          cd DBMLib
          cmake -B build/ -D os=linux
          cmake --build build/

      - name: Build for linux
        run: |
          g++ -fPIC -shared -I"jdk/src/java.base/unix/native/include" -I"jdk/src/java.base/share/native/include" -I"DBMLib/include" DBMLib/lib/lib_DBMLib.cpp DBMLib/libs/linux/*.a -o src/libDBM.so
      - name: Upload libDBM.so 
        uses: actions/upload-artifact@v2
        with:
          name: dbm-jni
          path: src/libDBM.so

  build-dbm-windows:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install compiler tools
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake make mingw-w64
      - name: Clone java JDK
        uses: actions/checkout@v2
        with:
          repository: openjdk/jdk
          path: jdk

      - name: Compile UDBM for Windows
        run: |
          cd DBMLib
          cmake -B build/ -D os=windows -D CMAKE_TOOLCHAIN_FILE=toolchain-x86_64-w64-mingw32.cmake
          cmake --build build/

      - name: Build for windows
        run: |
          x86_64-w64-mingw32-g++ -fPIC -shared -I"jdk/src/java.base/windows/native/include" -I"jdk/src/java.base/share/native/include" -I"DBMLib/include" DBMLib/lib/lib_DBMLib.cpp DBMLib/libs/windows/*.a -o src/DBM.dll
      - name: Upload DBM.dll 
        uses: actions/upload-artifact@v2
        with:
          name: dbm-jni
          path: src/DBM.dll