name: Build artifacts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-jcdd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install compiler tools
        run: |
          sudo apt-get update
          sudo apt-get install cmake openjdk-11-jdk g++ mingw-w64-x86-64-dev mingw-w64-tools g++-mingw-w64-x86-64

      - name: Compile JCDD for Linux
        run: |
          cd JCDD && mkdir build
          ./getlibs.sh
          cmake -B build/
          cmake --build build/

      - name: Compile JCDD for Windows
        run: |
          cd JCDD && mkdir build-win
          ./getlibs-win.sh
          cmake -B build-win/
          cmake --build build-win/

      - name: Upload JCDD Linux
        uses: actions/upload-artifact@v2
        with:
          name: jcdd-linux
          path: JCDD/build/jcdd/lib/*

      - name: Upload JCDD Windows
        uses: actions/upload-artifact@v2
        with:
          name: jcdd-windows
          path: JCDD/build-win/jcdd/lib/*
